config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'manhattan/index' => 'manhattan#index'
  get 'brooklyn/index' => 'brooklyn#index'
  get 'queens/index' => 'queens#index'
  get 'bronx/index' => 'bronx#index'
  get 'westchester/index' => 'westchester#index'

  get 'manhattan/show' => 'manhattan#show'

  resources :spot

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :spot
end

app/models/spot.rb
class Spot < ActiveRecord::Base
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bronx_controller.rb
class BronxController < ApplicationController
def index

  @spots = Spot.all

  @spot = @spots.borough(params[:borough]) if params[:borough].present?
end

def show
@spots = Spot.all
@spot = Spot.find(params[:borough])



end


end

app/controllers/brooklyn_controller.rb
class BrooklynController < ApplicationController

def index

  @spots = Spot.all

  @spot = @spots.borough(params[:borough]) if params[:borough].present?
end

def show
@spots = Spot.all
@spot = Spot.find(params[:borough])



end



end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
end


end

app/controllers/manhattan_controller.rb
class ManhattanController < ApplicationController

def index

  @spots = Spot.all

  @spot = @spots.borough(params[:borough]) if params[:borough].present?
end

def show
@spots = Spot.all
@spot = Spot.find(params[:id])



end




end

app/controllers/queens_controller.rb
class QueensController < ApplicationController

def index

  @spots = Spot.all

  @spot = @spots.borough(params[:borough]) if params[:borough].present?
end

def show
@spots = Spot.all
@spot = Spot.find(params[:borough])



end



end

app/controllers/spot_controller.rb
class SpotController < ApplicationController

def index
@spots = Spot.all
end

def show
@spots = Spot.all
@spot = Spot.find(params[:id])
end


end

app/controllers/westchester_controller.rb
class WestchesterController < ApplicationController

def index

  @spots = Spot.all

  @spot = @spots.borough(params[:borough]) if params[:borough].present?
end

def show
@spots = Spot.all
@spot = Spot.find(params[:borough])



end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boroughs_helper.rb
module BoroughsHelper
end

app/helpers/bronx_helper.rb
module BronxHelper
end

app/helpers/brooklyn_helper.rb
module BrooklynHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/manhattan_helper.rb
module ManhattanHelper
end

app/helpers/queens_helper.rb
module QueensHelper
end

app/helpers/spot_helper.rb
module SpotHelper
end

app/helpers/westchester_helper.rb
module WestchesterHelper
end

app/views/bronx/index.html.erb
<!--     SIDE BAR -->
<nav>
<%= link_to "( ͡° ͜ʖ //", root_path, :class => 'links' %>
<%= link_to "brooklyn //", brooklyn_index_path, :class => 'links' %>
<%= link_to "manhattan //", manhattan_index_path, :class => 'links' %>
<%= link_to "queens //",queens_index_path, :class => 'links' %>
<%= link_to "westchester", westchester_index_path, :class => 'links' %>
</nav>


<i><div class="bronx">b r o n x</div></i>



<!-- display spot names -->
<div class = "spots">
<% @spots.each do |s| %>
      <% if s.borough == "Bronx" %>
        <%= link_to "#{s.name}", spot_path(s.id), :class => 'spot_link' %>
        <% end %>
    <% end %>
</div>

    <iframe width="640" height="469" src="https://www.youtube.com/embed/f-_141WPXuU" frameborder="1px"</iframe>

app/views/brooklyn/index.html.erb
<!-- sidebar -->
<nav>
<%= link_to "( ͡° ͜ʖ //", root_path, :class => 'links' %>
<%= link_to "bronx //", bronx_index_path, :class => 'links' %>
<%= link_to "manhattan //", manhattan_index_path, :class => 'links' %>
<%= link_to "queens //",queens_index_path, :class => 'links' %>
<%= link_to "westchester", westchester_index_path, :class => 'links' %>

</nav>


<i><div class="borough_name">b r o o k l y n</div></i>


<!-- display spot names -->
<div class="spots">
<% @spots.each do |s| %>
      <% if s.borough == "Brooklyn" %>
        <%= link_to "#{s.name}", spot_path(s.id), :class => 'spot_link' %>
        <% end %>
    <% end %>
</div>

<iframe width="640" height="469" src="https://www.youtube.com/embed/xQ7_tU-0k20" frameborder="1px"</iframe>

app/views/home/index.html.erb
<div class="app_name">s p o t <span>( ͡° ͜ʖ</span> h e c k</div>

<div class="boroughs">
<%= link_to "manhattan", manhattan_index_path, :class => "manhattan_home_link" %>
<br>
<br>
<%= link_to "brooklyn", brooklyn_index_path, :class => "bk_home_link" %>
<br>
<br>
<%= link_to "queens", queens_index_path, :class => "queens_home_link" %>
<br>
<br>
<%= link_to "bronx", bronx_index_path, :class => "bx_home_link" %>
<br>
<br>
<%= link_to "the farm", westchester_index_path, :class => "westchester_home_link" %>


</div>

<div class="gifs">
<div class="manhattangif"><%= image_tag("manhattan1.gif") %></div>
<div class="queensgif"><%= image_tag("fmp1.gif") %></div>
<div class="westchestergif"><%= image_tag("westchester1.gif") %></div>

<div class="bkgif"><%= image_tag("bk1.gif") %></div>

<div class="bxgif"><%= image_tag("pun1.gif") %></div>
</div>

app/views/manhattan/index.html.erb
<!--     SIDE BAR -->
<nav>
<%= link_to "( ͡° ͜ʖ //", root_path, :class => 'links' %>
<%= link_to "bronx //", bronx_index_path, :class => 'links' %>
<%= link_to "brooklyn //", brooklyn_index_path, :class => 'links' %>
<%= link_to "queens //",queens_index_path, :class => 'links' %>
<%= link_to "westchester", westchester_index_path, :class => 'links' %>
</nav>


<i><div class="manhattan">m a n h a t t a n</div></i>


<!-- display spot names -->
    <div class = "spots">
    <% @spots.each do |s| %>
      <% if s.borough == "Manhattan" %>
        <%= link_to "#{s.name}", spot_path(s.id), :class => 'spot_link' %>
        <% end %>
    <% end %>
    </div>

    <iframe src="https://player.vimeo.com/video/132168306" width="640" height="469" frameborder="1px"</iframe>

app/views/queens/index.html.erb
<!-- sidebar -->
<nav>
<%= link_to "( ͡° ͜ʖ //", root_path, :class => 'links' %>
<%= link_to "brooklyn //", brooklyn_index_path, :class => 'links' %>
<%= link_to "bronx //", bronx_index_path, :class => 'links' %>
<%= link_to "manhattan //", manhattan_index_path, :class => 'links' %>
<%= link_to "westchester", westchester_index_path, :class => 'links' %>
</nav>

<i><div class="borough_name">q u e e n s</div></i>


<!-- display spot names -->
<div class="spots">
<% @spots.each do |s| %>
      <% if s.borough == "Queens" %>
        <%= link_to "#{s.name}", spot_path(s.id), :class => 'spot_link' %>
        <% end %>
    <% end %>
</div>

<iframe width="640" height="469" src="https://www.youtube.com/embed/9dKOl9xX0lA" frameborder="1px"</iframe>

app/views/spot/show.html.erb
    
    <div class="individual_spot_nav">
    
    <%= link_to "( ͡° ͜ʖ //", root_path, :class => 'links' %>
    <%= link_to "brooklyn //", brooklyn_index_path, :class => 'links' %>
    <%= link_to "bronx //", bronx_index_path, :class => 'links' %>
    <%= link_to "manhattan //", manhattan_index_path, :class => 'links' %>
    <%= link_to "queens //",queens_index_path, :class => 'links' %>
    <%= link_to "westchester ", westchester_index_path, :class => 'links' %>
    </div>

  <i><div class="spot_name"><%= @spot.name %></div></i>

  
<div class="info_bar">
  
<b><div class="location">Location:</div></b>
<br>
  <div class="spot_location"><%= @spot.location %></div>

  <br>

  <b><div class="description">Description:</div></b>

  <div class="spot_description"><%=raw @spot.description %></div>

  <br>

  <b><div class="bust_level">Bust:</div></b>
  <br>
  <div class="bust_image"><%= image_tag(@spot.bust) %></div>
</div>

  
<!-- picture slider -->


  <div class ="slider" style="width: 800px; height: 500px; margin-left: 50px; margin-left: 450px;">
  <div><%= image_tag(@spot.image1, width: '800', height: '500') %></div>
  <div><%= image_tag(@spot.image2, width: '800', height: '500') %></div>
  <div><%= image_tag(@spot.image3, width: '800', height: '500') %></div>
  <div><%= image_tag(@spot.image4, width: '800', height: '500') %></div>
  </div>

app/views/westchester/index.html.erb
<!-- sidebar -->
<nav>
    <%= link_to "( ͡° ͜ʖ //", root_path, :class => 'links' %>
    <%= link_to "brooklyn //", brooklyn_index_path, :class => 'links' %>
    <%= link_to "bronx //", bronx_index_path, :class => 'links' %>
    <%= link_to "manhattan //", manhattan_index_path, :class => 'links' %>
    <%= link_to "queens",queens_index_path, :class => 'links' %>
    </nav>


<i><div class="borough_name">w e s t c h e s t e r</div></i>



<!-- display spot names -->
<div class="spots">
<% @spots.each do |s| %>
      <% if s.borough == "Westchester" %>
        <%= link_to "#{s.name}", spot_path(s.id), :class => 'spot_link' %>
        <% end %>
    <% end %>
</div>

<iframe width="640" height="469" src="https://www.youtube.com/embed/5RkC0YyyuBs" frameborder="1px"</iframe>